name: Build TWRP Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Your Repository
      uses: actions/checkout@v4

    - name: Cleanup Space
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /opt/ghc
        sudo apt clean

    - name: Install Build Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc build-essential libssl-dev libxml2-utils git zip unzip curl python3 python-is-python3

    - name: Set up Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Sync TWRP Source
      run: |
        mkdir twrp
        cd twrp
        git config --global user.email "gh-actions@example.com"
        git config --global user.name "GitHub-Actions"
        # استخدام سورس TWRP المتوافق مع أندرويد 11
        ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 --depth=1
        ~/bin/repo sync -c -j$(nproc) --no-tags --no-clone-bundle

    - name: Move Device Tree to Source
      run: |
        # إنشاء المسار الكامل للجهاز داخل سورس TWRP
        mkdir -p twrp/device/mediatek/m7332
        
        # نسخ كافة الملفات والمجلدات (بما فيها recovery/root) من الواجهة
        # تم استخدام أمر cp -R لضمان النسخ المتكرر للمجلدات الداخلية
        # مع استثناء مجلد 'twrp' لتجنب النسخ اللانهائي داخل نفسه
        find . -maxdepth 1 -not -name 'twrp' -not -name '.' -not -name '..' -not -name '.git' -not -name '.github' -exec cp -R {} twrp/device/mediatek/m7332/ \;
        
        # التأكد من نظافة المسار من ملفات الجيت الزائدة
        rm -rf twrp/device/mediatek/m7332/.github
        rm -rf twrp/device/mediatek/m7332/.git

    - name: Build TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        
        export MY_PRODUCT="twrp_m7332"
        export ALLOW_MISSING_DEPENDENCIES=true
        export BUILD_BROKEN_MISSING_PGO_STATS_ERROR=true
        export BUILD_BROKEN_DUP_RULES=true
        # الأوامر السحرية لتجاهل أخطاء VTS و Soong
       
        export TEMPORARY_DISABLE_PATH_RESTRICTIONS=true
        export SELINUX_IGNORE_NEVERALLOWS=true
        
        lunch ${MY_PRODUCT}-eng || lunch ${MY_PRODUCT}-userdebug
        rm -rfhardware/interfaces/automotive
        # قبل البناء، سنقوم بحذف مجلدات الاختبار التي تسبب المشاكل
        rm -rf hardware/interfaces/audio
        rm -rf hardware/interfaces/camera
        # (اختياري: يمكنك إضافة المزيد من rm -rf للمجلدات التي تظهر في الخطأ)

        # البدء بالبناء
        mka recoveryimage -j$(nproc)




    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-m7332-Final-Result
        # رفع ملف الـ recovery.img الناتج مهما كان اسم المجلد الفرعي
        path: twrp/out/target/product/*/recovery.img
